version: '3.8'

networks:
  recepciona: # Rede para comunicação entre os containers
    driver: bridge

services:
  postgres:
    image: postgres:17.2
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: adrianovictorn
      POSTGRES_PASSWORD: vitor159@
      POSTGRES_DB: recepciona_db
    ports:
      - "5432:5432"
    networks:
      - recepciona
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adrianovictorads@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    networks:
      - recepciona
    depends_on:
      - postgres

volumes:
  postgres_data:
